- src/modules/communication/GcodeDispatch.cpp
- src/modules/communication/GcodeDispatch.h
wait for queue empty before doing M500
> tweak header file includes

- src/modules/communication/GcodeDispatch.cpp
- src/modules/tools/zprobe/ThreePointStrategy.cpp
- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
Also clear bed plane on three point bed levelling
> Fix ever increasing config-override file size

- src/libs/Network/uip/plan9/plan9.cpp
- src/libs/Network/uip/plan9/plan9.h
Please pull these improvements to the plan9 fs.
1. PSOCK receive/send thread for performance and better tcp handling
2. Fletcher64 hash used for file identifier (saves memory)
> Plan9 improvements

- src/libs/Network/uip/plan9/plan9.cpp
- src/libs/Network/uip/plan9/plan9.h
* More and better error checking
* Memory restrictions to ensure that we don't run out of it
Please pull :)
> Improvements to the plan9 library (More checks, memory restrictions)

- src/modules/communication/GcodeDispatch.cpp
> gcode dispatch: send ok for M28/M29 upload gcodes

- src/modules/tools/zprobe/ZGridStrategy.cpp
- src/modules/tools/zprobe/ZGridStrategy.h
Related to consecutive fopen on SD.
> Removed file read during handle_config to prevent hang at boot.

- src/modules/tools/zprobe/ZGridStrategy.cpp
Works without endstops module.
> Zgrid probing fixes

- src/modules/tools/zprobe/ZGridStrategy.cpp
- src/modules/tools/zprobe/ZGridStrategy.h
Initial commits.  Circular beds, and center 0,0 to follow
> Zgrid repairs according to #649

- src/modules/robot/arm_solutions/MorganSCARASolution.cpp
- src/modules/robot/arm_solutions/MorganSCARASolution.h
- src/modules/tools/scaracal/SCARAcal.cpp
- src/modules/tools/scaracal/SCARAcal.h
Added scale functionality in M665, and 
M366: Convert trim to real home offsets
> SCARA calibration updates.  

- src/modules/tools/zprobe/ZGridStrategy.cpp
- src/modules/tools/zprobe/ZGridStrategy.h
Added homing options to ZGrid:
NOHOME
HOMEXY
HOMEXYZ (Default)
> ZGrid: add homing options

- src/modules/tools/zprobe/ZGridStrategy.cpp
Repaired ZGrid probe offset after G32 probing
> ZGrid maintenance

- src/libs/Adc.cpp
- src/modules/tools/temperaturecontrol/PID_Autotuner.cpp
- src/modules/tools/temperaturecontrol/PID_Autotuner.h
- src/modules/tools/temperaturecontrol/Thermistor.cpp
- src/modules/tools/temperaturecontrol/Thermistor.h
M305 will now also show the minmax temps recorded since last M305 good for testing for noise and PID performance
> Tighten up autopid to produce better results

- src/modules/communication/GcodeDispatch.cpp
- src/modules/communication/GcodeDispatch.h
- src/modules/communication/utils/Gcode.cpp
- src/modules/communication/utils/Gcode.h
- src/modules/robot/Conveyor.cpp
- src/modules/robot/Robot.cpp
- src/modules/tools/drillingcycles/Drillingcycles.cpp
- src/modules/tools/endstops/Endstops.cpp
- src/modules/tools/extruder/Extruder.cpp
- src/modules/tools/scaracal/SCARAcal.cpp
- src/modules/tools/spindle/Spindle.cpp
- src/modules/tools/temperaturecontrol/PID_Autotuner.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
- src/modules/tools/toolmanager/ToolManager.cpp
- src/modules/tools/zprobe/ZGridStrategy.cpp
- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/utils/player/Player.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
This was not required, and was not well supported anyway, many commands reported unhandled when they were.
This was an ugly hack and needed to go.
> remove the unhandled gcode hack, and all the cruft it required

- src/modules/tools/zprobe/ZGridStrategy.cpp
Added constant equal to half the multiplier to ensure the conditions are not foiled by floating point problems.
> ZGrid fine grid fix

- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/tools/zprobe/ZProbe.h
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
> zprobe: add custom feedrate support (G30 Fxyz)

- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/tools/zprobe/ZProbe.h
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
> zprobe: add zprobe.return_feedrate config option

- src/modules/tools/zprobe/ZProbe.cpp
Also adds support for storing probe configuration
to config-override via M500
;Probe feedrates slow/fast/return (mm/sec):
M670 S0.50 K2.00 R2.50
;Probe max_z (mm):
M670 Z200.00
;Probe height (mm):
M670 H2.00
Signed-off-by: Richard Marko <rmarko@fedoraproject.org>
Depends on #704.
> zprobe: add configuration via M670

- src/modules/robot/arm_solutions/BaseSolution.h
- src/modules/robot/arm_solutions/CartesianSolution.cpp
- src/modules/robot/arm_solutions/CartesianSolution.h
- src/modules/robot/arm_solutions/ExperimentalDeltaSolution.cpp
- src/modules/robot/arm_solutions/ExperimentalDeltaSolution.h
- src/modules/robot/arm_solutions/HBotSolution.cpp
- src/modules/robot/arm_solutions/HBotSolution.h
- src/modules/robot/arm_solutions/LinearDeltaSolution.cpp
- src/modules/robot/arm_solutions/LinearDeltaSolution.h
- src/modules/robot/arm_solutions/MorganSCARASolution.cpp
- src/modules/robot/arm_solutions/MorganSCARASolution.h
- src/modules/robot/arm_solutions/RotatableCartesianSolution.cpp
- src/modules/robot/arm_solutions/RotatableCartesianSolution.h
- src/modules/robot/arm_solutions/RotatableDeltaSolution.cpp
- src/modules/robot/arm_solutions/RotatableDeltaSolution.h
and actuator_to_cartesian conversion functions
> add const qualifier to input argument to cartesian_to_actuator

- src/modules/tools/endstops/Endstops.cpp
Also fixed limit switches working with Deltas. No extra trim needed now.
> Oskar linde feature/soft soft endstop fixed limits

- src/modules/tools/endstops/Endstops.cpp
This changes the physical motion of the actuators when applying endstop-trim into a software compensation. This makes positive endstop trim values not cause G28 to crash into the endstops.
> Make soft endstops truly soft

- src/modules/tools/zprobe/ZGridStrategy.cpp
optimise code and repaired probe removal position
> ZGrid repair probe removal position

- src/modules/tools/extruder/Extruder.cpp
> don't do immediate G92 on extruder if not enabled

- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/extruder/Extruder.cpp
- src/modules/utils/player/Player.cpp
- src/modules/utils/player/Player.h
fix speed issues in extruder after suspend resume when left in relative mode
> use push/pop state to save current state on suspend/resume

- build/common.mk
For some reason was not able to merge the original PR.
> applied PR  #607 manually to update the way nano libs are pulled in

- src/modules/tools/zprobe/ThreePointStrategy.cpp
- src/modules/utils/panel/screens/ProbeScreen.cpp
Print confirmation for clearing leveling plane
> Allow LCD probe status to display longer status lines

- src/modules/tools/temperatureswitch/TemperatureSwitch.cpp
- src/modules/tools/temperatureswitch/TemperatureSwitch.h
no longer required to keep a vector of temperaturecontrollers
> reduce the memory usage of each temperatureswitch.

- src/modules/robot/Robot.h
- src/modules/tools/zprobe/DeltaCalibrationStrategy.cpp
- src/modules/tools/zprobe/ZProbe.cpp
add G29.1 to output probe results in a format better suited for pasting in external programs
> change selection of zprobe strategies from subcodes to Pn parameter

- src/modules/robot/Robot.cpp
- src/modules/utils/player/Player.cpp
fixes the position setting after an abrupt abort.
also invalidates suspend if G28 (home) is issued while suspended.
> fix issue #818

- ConfigSamples/AzteegX5Mini.delta/Version2/config
- ConfigSamples/AzteegX5Mini/Version2/config
- src/modules/utils/simpleshell/SimpleShell.cpp
also add a -d nnn parameter for the cat command
> add version2 config for azteeg x5 mini

- src/modules/robot/arm_solutions/RotaryDeltaSolution.cpp
- src/modules/tools/zprobe/DeltaCalibrationStrategy.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
useful for debugging arm solutions
added warning if delta radius calibration did not resolve
> add command:- get [ik|fk] [-m] x,y,z

- src/libs/StepTicker.cpp
- src/libs/StepTicker.h
- src/libs/StepperMotor.cpp
- src/libs/StepperMotor.h
- src/libs/utils.cpp
- src/libs/utils.h
- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/tools/zprobe/ZProbe.h
implement G38.2 for X or Y moves, so probing sideways to get center or size
> Introduce the ability to stop a planner move based on a defined function

- src/libs/SlowTicker.cpp
- src/libs/SlowTicker.h
- src/libs/StepTicker.cpp
- src/main.cpp
refactor the slowticker setup
Fixes PR  #853
> fix when slow ticker gets started

- src/libs/Kernel.h
- src/libs/StepperMotor.cpp
- src/main.cpp
- src/makefile
- src/modules/communication/GcodeDispatch.cpp
- src/modules/communication/utils/Gcode.cpp
- src/modules/robot/Block.cpp
- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/temperaturecontrol/predefined_thermistors.h
As the title says, fixes some typos and minor consistency issues I noticed while going through the codebase.
> Fixed some typos and minor consistency issues.

- src/modules/tools/zprobe/DeltaGridStrategy.cpp
if the grid radius is different in saved file override the config radius
> Save the grid size and grid radius to the delta.grid file

- ConfigSamples/Smoothieboard/config
> Very minor modifications to comments in config

- src/modules/utils/motordrivercontrol/MotorDriverControl.cpp
- src/modules/utils/motordrivercontrol/MotorDriverControl.h
- src/modules/utils/motordrivercontrol/drivers/DRV8711/drv8711.cpp
- src/modules/utils/motordrivercontrol/drivers/DRV8711/drv8711.h
- src/modules/utils/motordrivercontrol/drivers/TMC26X/TMC26X.cpp
- src/modules/utils/motordrivercontrol/drivers/TMC26X/TMC26X.h
drv8711 has gain and sense_resistor
TMC has sense_resistor
> refactor to allow for driver specific config settings

- src/modules/communication/GcodeDispatch.cpp
- src/modules/tools/zprobe/DeltaGridStrategy.cpp
other minor updates to comments or info print outs
NOTE S1000 will currently be ignored but return ok, the Spindle module needs to be updated to handle it correctly.
> Allow S1000 on a line by itself or in mutli gcode lines

- src/libs/utils.cpp
- src/libs/utils.h
- src/modules/communication/GcodeDispatch.cpp
- src/modules/tools/zprobe/DeltaGridStrategy.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
refactor to where and when it is processed, and make it use on_gcode event
May fix #908
> attempt to make M501 use less stack.

- src/modules/robot/Robot.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
> make the cnc test circle use G2

- src/modules/tools/extruder/Extruder.cpp
- src/modules/tools/extruder/Extruder.h
> make firmware retraction independent of any flow rate setting

- src/libs/StepperMotor.cpp
With dirpin inverted the value of direction was wrong until manually set.
> Fixed StepperMotor direction being undefined

- ConfigSamples/AzteegX5Mini/Version2/config
- ConfigSamples/AzteegX5Mini/Version3/config
- ConfigSamples/Smoothieboard.delta/config
- ConfigSamples/Smoothieboard/config
- ConfigSamples/rotary.delta/config
- src/modules/robot/Conveyor.cpp
- src/modules/robot/Robot.cpp
- src/modules/tools/endstops/Endstops.cpp
- src/modules/utils/panel/PanelScreen.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
also some other refactors and bug fixes, see log.
> add gamma_max_travel for homing

- src/modules/utils/panel/screens/cnc/WatchScreen.cpp
> fix watchscree

- src/modules/robot/Robot.h
- src/modules/utils/panel/screens/ModifyValuesScreen.cpp
- src/modules/utils/panel/screens/ModifyValuesScreen.h
- src/modules/utils/panel/screens/cnc/LaserScreen.cpp
- src/modules/utils/panel/screens/cnc/LaserScreen.h
- src/modules/utils/panel/screens/cnc/WatchScreen.cpp
add set S value menu item to laser screen
fix single entry ModifyValuesScreen when not immediate set
> fix modifyvalue screen, update laser screen

- src/libs/USBDevice/USBSerial/CircBuffer.h
- src/libs/USBDevice/USBSerial/USBSerial.cpp
gives simple line editing to commands
> add BS and DEL to the USB serial to delete last character entered

- src/modules/utils/panel/screens/3dprinter/WatchScreen.cpp
- src/modules/utils/player/Player.cpp
Hopefully this PR will be a bit more strait forward than my last one.  I have a hard time thinking in seconds.  Whenever I would check the watch screen elapsed time, I would have to mentally do the calculations to convert the seconds into hours and minutes.  I decided to modify the watch screen and 'progress' command to display time in HH:MM:SS format.  I thought this might also be useful for others, so I'm submitting this PR in the hopes that it may be helpful.
> modified timestamp format to HH:MM:SS.

- src/modules/robot/Robot.cpp
G91 G10 L2 P1 X1 will add 1 to the G54 WCS X offset.
G90 G10 L2 P1 X1 will set to 1 to the G54 WCS X offset.
> Allow relative mode to affect G10 L2

- src/main.cpp
Just flashing this version will disable MSD if built with DISABLEMSD=1
> Make the nomsd build default to msd disabled

- src/libs/Kernel.h
- src/libs/USBDevice/USBSerial/USBSerial.cpp
- src/modules/utils/panel/screens/cnc/WatchScreen.cpp
The host should simply stop sending gcode to pause (as pronterface does).
> ignore ! and ~ as pause and resume do not work

- src/modules/tools/scaracal/SCARAcal.cpp
Adds the ability to individually calibrate steps per degree in Theta and Psi
> Improve Scara Calibration

- src/modules/robot/Robot.cpp
> pow -> powf
