Smoothieware/Smoothieware

- src/libs/Network/uip/Network.cpp
- src/libs/Network/uip/plan9/plan9.cpp
- src/libs/Network/uip/plan9/plan9.h
See #592 for the prior discussion.
1. Add the option `network.plan9.enable true` to the config.
2. Reset the smoothie
3. Mount with `mount -t 9p <smoothie-ip> /mnt/smoothie` and access `/mnt/smoothie` like a normal filesystem. Have fun!1!!
The filesystem will be synchronous which means everything will be written immediately to the SD and there is no possibility for incomplete writes etc. If your `9p.ko` Linux kernel module is compiled with debugging support you can also mount with the debug option, i.e. `mount -t 9p -o debug=0x200 <smoothie-ip> /mnt/smoothie`. The messages will appear in dmesg.
* The `Network` class was extended with calls to the plan9 handler
* The plan9 module was added which handles the 9p messages and relies on `opendir/fopen/fwrite` etc to access the filesystem.
1. …
> Plan9 filesystem support for Smoothieboard!

- src/libs/Network/uip/plan9/plan9.cpp
As requested. I think it is better to avoid the pragmas in general and to disable the warnings one by one.
> p9: get rid of warnings

- src/modules/tools/temperaturecontrol/predefined_thermistors.h
This thermistor is used by the following heated bed, which is available from Japan at eMakershop.
[Hex 170mm Dia. PCB Heated Bed](http://www.emakershop.com/browse/listing?l=1081)
> Added Vishay 100K thermistor

- src/modules/tools/temperaturecontrol/predefined_thermistors.h
also Beta are deprecated so removed the beta definition for new thermistor
> fixed the thermistor PR

- ConfigSamples/Smoothieboard/config
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.h
Added a way to specify a minimum temperature to protect against damaged thermistors. If not set, the machine will act as before.
> Thermistor safety (minimum temperatures)

- src/modules/robot/arm_solutions/MorganSCARASolution.cpp
- src/modules/robot/arm_solutions/MorganSCARASolution.h
Added config parameters to define regions close to the SCARA tower and the maximum reach in order to prevent arms colliding.
The arms will limit the movement and move around the obstacle if sent to a destination on the other side of such a region.
Making it configurable allows  the user to place system components in those regions without fear of collisions.
> Add configurable SCARA limits to MorganSCARASolution

- src/modules/utils/panel/screens/FileScreen.cpp
OS X leaves a lot of hidden files on the SD card, whether files are written directly to SD card or through USB. This is cluttering the panel and since the hidden files are of no use for Smoothie, I have added code to filter them out. This includes directories like .Trashes. I can't think of a reason why people would want to name their gcode files with a '.' in the beginning, so I don't think it will harm anyone. If it does, it can be customised using the config file, but this will add to the size of the code with little value.
> Not showing hidden files

- src/modules/communication/GcodeDispatch.cpp
Fixed parser bug to allow something like T1 M200 on a single line
As always if Tn appears anywhere on a line it switches the tool first then executes any commands on that line.
> Allow Tn as first command on a line, followed by any M or G command

- src/modules/tools/scaracal/SCARAcal.cpp
Repaired calculation error in Psi autocalibration.  Psi is a function of the "A" and "B" actuators and not only dependent on "B"
> SCARA calibration: Psi calculation bug fixed.

- src/modules/robot/Robot.cpp
No movement is performed when G03 is used and a full circle (end point is coincident with start point) is programmed. Problem found by Christoph Baumann and me.
> fixed arc problem with G03 - patched from grbl project

- src/libs/ADC/adc.cpp
- src/libs/ADC/adc.h
- src/libs/Adc.cpp
- src/libs/Adc.h
- src/modules/tools/temperaturecontrol/Thermistor.cpp
- src/modules/tools/temperaturecontrol/Thermistor.h
Refactored ADC to handle the filtering and averaging etc, removed from Thermistor.
Added better checks in Thermistor for open circuit thermistor, not just max ADC value.
Added oversampling to increase ADC resolution by 2 bits to 14bits.
Added better filtering for raw ADC values before they get oversampled.
Average last 4 oversampled readings when thermistor reads them, this flattens out the rate of change and improves the PID performance.
Removed the race condition on original ADC reads that could cause bad ADC values to randomly appear.
NOTE rerunning PID autotune is recommended after this change.
> Add adc oversampling and filtering and averaging

- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/extruder/Extruder.cpp
- src/modules/tools/extruder/Extruder.h
- src/modules/tools/extruder/ExtruderPublicAccess.h
- src/modules/utils/player/Player.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
Also adds speed limiting based on extruder max_speed in mm/sec.
Adds M203 Vxxx which sets the maximum Extruder volumetric rate to xxx mm³/sec
If a planned line exceeds the specified volumetric rate then the feedrate of the line is lowered to a point where the max volumetric setting in not exceeded, same with max_speed for the extruder.
M203 E0 will turn off the extruder speed check
M203 V0 will turn off volumetric limiting if in volumetric extrusion mode
defaults are M203 E50 (set in config) and V0
For now volumetric speed limit can only be set with M203 Vxxx (no config setting)
> Add speed limiting based on maximum extrusion rate in mm^3/sec

- ConfigSamples/AzteegX5Mini.delta/config
- ConfigSamples/AzteegX5Mini/config
- ConfigSamples/FirePick.delta/config
- ConfigSamples/Smoothieboard.delta/config
- ConfigSamples/Smoothieboard/config
- src/modules/tools/laser/Laser.cpp
- src/modules/tools/laser/Laser.h
This changes the config to work as described in issue #685.  It makes
the laser_module_max_power work as expected / documented, introduces
a minimum power setting, and scales the output between the two.
It should be backwards-compatible with existing configs, but I've not been
able to test it on a live machine yet.  Hopefully I'll be able to get it on a scope 
over the next couple of days to confirm operation.
> Changes to laser module PWM config.

- src/modules/utils/panel/screens/MainMenuScreen.cpp
Z Home Ofs is useful for fine adjustment of the "paper thickness" offset between head and bed, but the menu option needs higher precision for this to be usable from the panel. 10 µm seems like a reasonable level of precision for tweaking the first layer offset.
> Increase Z Home Ofs menu setting precision to 0.01 mm

- src/modules/tools/switch/Switch.cpp
- src/modules/tools/switch/Switch.h
failsafe_set_to 0 means on MRI crash or ON_HALT the pin is set low (default)
failsafe_set_to 1 means on MRI crash or ON_HALT the pin is set high
ignore_on_halt false means it will set the pin to the failsafe value on ON_HALT (default)
ignore_on_halt true means it will not set the pin on ON_HALT, it will be left in whatever state it was in
> added failsafe_set_to and ignore_on_halt to switch module config

- src/libs/PublicData.cpp
- src/libs/PublicData.h
- src/libs/PublicDataRequest.h
- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/robot/RobotPublicAccess.h
- src/modules/tools/switch/Switch.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
- src/modules/tools/toolmanager/ToolManager.cpp
- src/modules/utils/panel/screens/ControlScreen.cpp
- src/modules/utils/panel/screens/WatchScreen.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
now allows the caller to provide the data storage (a pointer to the data for the callee to store the result in) thi ssaves memory and allows multiple modules to respond to the same request.
refactor out Robot public data requests as they are not necessary as all modules have access to THEKERNEL->robot->...
> refactor get public data, to be slightly easier to use on callee side

- src/modules/tools/zprobe/ZGridStrategy.cpp
(1) Removed a redundant and incorrect move in the Z-probe.  If
cal_offset and/or probe_offset non-zero, then the calibration
loop first moves the extruder to the grid position, then makes
the correct move.  The first (incorrect) move has been removed.
(2) Corrected the getZOffset() routine, which would incorrectly
compute xIndex and yIndex if cal_offset_x or cal_offset_y is
negative ((int) is not the floor of a negative number).
(3) Improved getZOffset() by extrapolating points outside the
grid using the nearest grid square, such that for purposes of
correction, the plane of each outermost grid square effectively
extends to infinity.  The previous code returned zero for all
areas outside the grid, creating a discontinuity at the grid
boundary.
These changes were made especially for using …
> Improved ZGridStrategy:

- src/libs/Kernel.cpp
- src/libs/Kernel.h
- src/modules/communication/SerialConsole.cpp
- src/modules/communication/SerialConsole.h
Just as in GRBL ? on the serialport returns an immediate response like <Idle,MPos:5.529,0.560,7.000,WPos:1.529,-5.440,-0.000>
MPos is currently real time current actuator position, MPos is currently the last cartesian request coordinates.
^X will do a Halt like M112 and the kill button.
> add GRBL ^X and ? to serial uart handler

- src/modules/tools/temperaturecontrol/AD8495.cpp
The parameters have been changed to lower case to match the module name.
> Changed parameters to lower case

- src/modules/tools/filamentdetector/FilamentDetector.cpp
Allows the module to be instantiated if the bulge detector exists but
the encoder does not. Inhibits attachment to events for the encoder if
the encoder doesn’t exist.
I was able to test this with the bulge detector and it works as expected. I am not able to test the encoder functionality but that functionality should be completely untouched by this pull request.
> Allow bulge detector without encoder in filament detector

- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/tools/zprobe/ZProbe.h
implement G38.2 as per http://www.linuxcnc.org/docs/2.5/html/gcode/gcode.html#sec:G38-probe
For now only movements in Z negative direction are implemented.
Eventually this will be able to probe sideways (in X or Y) to do edge finding and center finding as done in CNC.
Unlike G30 this will not reset Z or go back to the original position, it leaves the head where ever the zprobe triggers and leaves the current position (M114) at whatever coordinates that position is.
> Feature/add g38.2 probe

- ConfigSamples/Snippets/ZprobeGrid.config
- src/modules/tools/zprobe/ZGridStrategy.cpp
- src/modules/tools/zprobe/ZGridStrategy.h
This pull request does the following:
1) repair Z offset after running routine with a well adjusted probe
2) Adds an optional manual probe attachment point
3) changes the normalisation method to zero the home position, preventing jerky movements on the first move after homing.
> Zgrid homing

- src/modules/tools/endstops/Endstops.cpp
Repaired the way scara systems home:
Z is not affected by inverse kinematics, thus can handle limits like non-delta systems if configured
> Scara endstops

- src/libs/Network/Drivers/LPC17XX_Ethernet.cpp
Previously the ethernet initialisation would clobber PINSEL2 + 3
registers, thereby removing functionality from any previously
configured pins. Eg. ADC4, ADC5 which use PINSEL3.
Signed-off-by: Paul Jones <paul@pauljones.id.au>
> Initalise ethernet pin connections correctly

- src/libs/StepperMotor.cpp
- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/endstops/Endstops.cpp
- src/modules/tools/temperaturecontrol/max31855.cpp
- src/modules/utils/panel/panels/UniversalAdapter.cpp
- src/modules/utils/panel/panels/rrdglcd/RrdGlcd.cpp
- src/modules/utils/panel/screens/WatchScreen.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
add reset_actuator_position() to allow manual homing and setting actuator specific positions
add G28.4 to allow manual setting of homing to actuator units (as opposed to cartesian coordinates)
add M1910.2 to move by the specified number of actuator units (as opposed to steps)
> add utility functions for manually controlling and setting odd arm solutions

- src/modules/tools/extruder/Extruder.cpp
if the zlift speed was different then it was left at that feedrate instead of resuming the previous feedrate.
> fix firmware retract with zlift setting feed rate

- src/libs/StepTicker.cpp
- src/libs/StepTicker.h
- src/libs/StepperMotor.cpp
- src/libs/StepperMotor.h
- src/modules/robot/Robot.cpp
- src/modules/robot/Robot.h
- src/modules/tools/zprobe/ZProbe.cpp
- src/modules/tools/zprobe/ZProbe.h
use a timer to check for probe and tell steppers to stop moving with a flag.
allow disabling of segmentation which is required to allow G38.x to work this way.
G38.x now works on deltas.
Check if probe was hit or miss more reliably in G38.x
> remove the fnc from stepticker used for probe checking.

- src/modules/tools/laser/Laser.cpp
- src/modules/tools/laser/Laser.h
A couple more small items for the laser module.
f95c9fc - Bug fix so the laser TTL pin stays on for the whole of an arc that comprises multiple blocks. Also ensures that TTL is turned off in the case of a HALT event, addressing issue #455.
5a2b237 and 15ddf50 - New optional laser-module_maximum_s_value that allows definition of what S value represents maximum laser power. Suits applications like CamBam that need an integer. Requested by another forum user. Defaults to existing 0-1 range if omitted.
> Allow setting for range for S parameter to control laser power

- src/modules/robot/Robot.cpp
Added G92.3 which sets the G92 offsets to the supplied X Y Z and is what M500 uses to save it.
> Fix saving of G92 with M500

- src/modules/tools/zprobe/DeltaGridStrategy.cpp
This should fix the "Failed to read grid radius" error when using M375 with delta-grid.
> Fix mistaken fwrite (should be fread)

- src/modules/robot/Robot.cpp
- src/modules/utils/player/Player.cpp
Fix the alpha_max_speed config setting so it is in mm/min not mm/sec (reverting bug introduced by PR #759
> Fix resume so it uses G53 to restore position

- src/modules/tools/endstops/Endstops.cpp
This is a bug fix when homing when in G20  mode.  It was making the
final move in inches instead of mm.  Homing should always bring you to
the same exact point whether you are in G20 or G21.  See
https://github.com/Smoothieware/Smoothieware/issues/952
> Fix Homing when in G20

- src/modules/tools/zprobe/DeltaGridStrategy.cpp
- src/modules/tools/zprobe/DeltaGridStrategy.h
adds 3 new config options to leveling-strategy.delta-grid:
max_x - defaults to value of grid_radius - Maximum travel from center of bed in +/-X direction 
max_y - defaults to value of grid_radius - Maximum travel from center of bed in +/-Y direction.
do_home - default True - Home at beginning of G31 call.
is_square - default False - turns off the check to not probe the corners (do not set on a delta with a round bed)
Caveat: 0,0 must be the center of the bed when using this leveling strategy.
> Permits cartesians to use delta-grid levelling strategy

- src/modules/tools/endstops/Endstops.cpp
This is just a minor refinement.  Since G28.2 (G28 in GRBL mode) only are intended to work for X and Y, then Z shouldn't be saved with the predefined position.
> G28.1 minor adjustment

- src/libs/SlowTicker.cpp
- src/libs/StepTicker.cpp
- src/libs/StepTicker.h
- src/libs/StepperMotor.cpp
- src/modules/communication/GcodeDispatch.cpp
- src/modules/utils/simpleshell/SimpleShell.cpp
> Clear current_tick when halted, or on start of new block

- src/libs/USBDevice/USBSerial/USBSerial.cpp
Regarding issue  #996: 
When exactly 64 bytes are sent, it isn't flushed immediately.
(it is sent later, whenever we have more bytes to send)
If the data is 63 or less bytes, then it is flushed immediately.
This is a problem if the user is waiting for an immediate response from Smoothie.
For example, when sending the '?' character to get the location.
This "fix" is a work-around: we split the data into packets
of 63 bytes or less.  The actual bug should probably be hunted down
and properly fixed.
Other people have hit this problem.  E.g.
https://community.nxp.com/message/360747
> "Fix" problem with flushing 64 byte packets

- src/modules/utils/simpleshell/SimpleShell.cpp
Added 'ok' response for '$H' command.  As far as I can tell, grbl sends back an ok after a homing cycle.  Currently, smoothie was not (when using the '$H" command), which was creating issues with bCNC having any command immediately following homing commands to be stuck in the send buffer.
> grbl mode homing response

- src/modules/robot/Robot.cpp
Allows setting of G92 offset from the config for offsetting the workspace coordinate system.
Will be overidden with M500 if the save_g92 true is on config
> add a set_g92 x,y,z to config

- README.creole
Was linking to HowToFileIssues.md which was renamed in these commits 7bb7936875 3fd39027e to ISSUE_TEMPLATE.md
> Fix broken link in README (HowToFileIssues.md)

- src/modules/utils/simpleshell/SimpleShell.cpp
- src/modules/utils/simpleshell/SimpleShell.h
@arthurwolf requested that I implement the `mkdir` command for the Smoothieware shell.  Presented for your consideration is a basic `mkdir` implementation on the `SimpleShell`.  This function takes a single parameter, the path of the directory to be created.  It may be an absolute or relative path.  There is no `-p` or other special arguments/flags.  If the path to the folder to be created does not exist, the command will fail.
> implemented the 'mkdir' command on the shell.

- src/modules/robot/Conveyor.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
Works around a bug or maybe a race condition where kill will wait indefinitely for a motor to stop, even though all motors have stopped.
> workaround to handle kill and not wait for motors to stop

- src/libs/Kernel.cpp
- src/libs/StepTicker.cpp
- src/libs/StepperMotor.h
- src/modules/robot/Conveyor.cpp
- src/modules/robot/Conveyor.h
Issue was ON_HALT being blocked in conveyor waiting for motors to stop, but that meant the ON_Halt was not being delivered to the extruder steppermotor, so it was not seen as being stopped.
> Better and correct fix for Kill hanging on E moving

- ConfigSamples/AzteegX5Mini.delta/Version3/config
- ConfigSamples/AzteegX5Mini/Version3/config
- ConfigSamples/Smoothieboard.delta/config
- ConfigSamples/Smoothieboard/config
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.h
This fixes the issue where changing the temp causes ON_HALT.
- It refactors slightly to optimize the case where runaway is disabled.
- Adds a timeout for over temp runaway which should mitigate issues where a temporary noise glitch would cause a HALT.
- Allows for setting the temp lower than it was providing a separate timeout for cooldown vs heatup.
- Allows for some noise before triggering ON_HALT for range errors.
- Increases the maximum heating and cooling timeout to about 34 minutes
> simple fix for the runaway issue.

- ConfigSamples/Snippets/panel.config
- src/modules/utils/panel/Panel.cpp
- src/modules/utils/panel/Panel.h
- src/modules/utils/panel/screens/3dprinter/WatchScreen.cpp
I have found that when a print is in progress, I have more interest in the Extruder position than the X and Y positions (which are changing too rapidly).  I modified the watch screen to display the X, Y and Z positions when the printer is idle, and the Extruder and Z positions when printing.
I present this for your consideration, in case anyone else would find it useful.
> modified watch screen to display extruder when printing.

- src/generate-version.sh
Relevant discussion is in #1057 .
**Tests:**
+ Original `git log --pretty=format:%h -1`:
```
$ strings LPC1768/main.bin | grep -i $(git log --pretty=format:%h -1)
edge-27d3f52
```
+ Patched `git rev-parse --short=7 HEAD`:
```
$ strings LPC1768/main.bin | grep -i $(git rev-parse --short=7 HEAD)
edge-27d3f52
```
+ Original `git log --pretty=format:%h -1`:
```
BUILD ERROR
```
+ Patched `git rev-parse --short=7 HEAD`:
```
$ strings LPC1768/main.bin | grep -i $(git rev-parse --short=7 HEAD)
edge-0e82de9
```
> Support for signed commit in versioning script

- src/modules/tools/zprobe/DeltaCalibrationStrategy.cpp
Log excerpt from compilation using default arm toolset available on Fedora:
$ arm-none-eabi-g++ --version
arm-none-eabi-g++ (Fedora 6.1.0-2.fc24) 6.1.0
compiling modules/tools/zprobe/DeltaCalibrationStrategy.cpp
modules/tools/zprobe/DeltaCalibrationStrategy.cpp: In member function 'bool DeltaCalibrationStrategy::probe_delta_points(Gcode*)':
modules/tools/zprobe/DeltaCalibrationStrategy.cpp:99:19: error: 'isnan' was not declared in this scope
if(isnan(bedht)) return false;
^
modules/tools/zprobe/DeltaCalibrationStrategy.cpp:117:19: error: 'NAN' was not declared in this scope
float last_z= NAN;
^~~
modules/tools/zprobe/DeltaCalibrationStrategy.cpp:137:24: error: 'isnan' was not declared in this scope
if(isnan(last_z)) {
^
modules/tools/zprobe/DeltaCalibrationStrategy.cpp:140:58: error: …
> Fix error: 'isnan' was not declared in this scope

- src/modules/tools/endstops/Endstops.cpp
Scara homing requires homing in the actuator space.  This pull request uses the axis space temporarily to perform homing.
As per guidelines by wolfmanjm
> Repair SCARA homing on new ABC endstops.cpp

- src/modules/robot/Robot.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.cpp
- src/modules/tools/temperaturecontrol/TemperatureControl.h
One issue people run into is if the bed is not well PID tuned it may sit a little above the target temperature set. This becomes an issue if the bed is still hot and the temp is set, the runaway detection will go into cool down mode and timeout because the temp never drops below or reaches the set point.
By adding a fudge factor it, by default, only needs to get within 1°C of the set temp to change state.
A new optional configuration setting of `runaway_error_range` can be set to change the fudge factor.
**NOTE** that by default cool down mode is disabled.
Also changed G4 Pxxx to be float seconds when in grbl compatibility mode.
> add a configurable range for the runaway temp checks
